services:
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - timescaledb_data:/var/lib/postgresql/data

  sensor-api:
    build: .
    container_name: sensor-api
    environment:
      - DATABASE_CREDENTIALS=${DATABASE_CREDENTIALS}
    depends_on:
      - timescaledb
    network_mode: host
    restart: unless-stopped

volumes:
  timescaledb_data:
